name: build
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event_name == 'push'}}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install dependencies
        run: |
          pipenv install --deploy --dev
      - name: Run test suite
        run: |
          pipenv run pytest
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: ${{ github.event_name == 'push'}}
    steps:
      - name: Run black formatter
        uses: rickstaa/action-black@v1.3.3

  coverage:
      runs-on: ubuntu-latest
      timeout-minutes: 10
      if: ${{ github.event_name == 'pull_request'}}
      steps:
        - name: Pytest Coverage Commentator
          uses: coroo/pytest-coverage-commentator@v1.0.2